### ISSUE TITLE
README example is outdated

### ISSUE THREAD

**Issue by hut8** [Erutuon/parse-mediawiki-sql#3]
First, I have to say: I was really surprised this crate existed, and you did a great job with it. Thanks so much for a great project!

```rust
use parse_mediawiki_sql::{
    iterate_sql_insertions,
    schemas::Page,
    types::{PageNamespace, PageTitle},
    utils::memory_map,
};
```

I'm pretty sure `types` should be `field_types`. I'll open a PR shortly.

**Comment by Erutuon** [comment]
Thanks for spotting this! `cargo test` doesn't try to compile the code in the readme so I missed the old module name even though I made other changes to the code. It would be nice if there were a way to test the code in the readme.

Glad you like the crate. Let me know if there are any problems with usability and so on.
